#ifndef _ATM328PTIMERCLOCKSOURCE_H_
#define _ATM328PTIMERCLOCKSOURCE_H_

typedef enum {
    TIMER_CLOCK_INTERNAL_PRESCALE_1    = 0x01,
    TIMER_CLOCK_INTERNAL_PRESCALE_8    = 0x02,
    TIMER_CLOCK_INTERNAL_PRESCALE_64   = 0x03,
    TIMER_CLOCK_INTERNAL_PRESCALE_256  = 0x04,
    TIMER_CLOCK_INTERNAL_PRESCALE_1024 = 0x05,
    TIMER_CLOCK_EXTERNAL_FALLING       = 0x06,
    TIMER_CLOCK_EXTERNAL_RISING        = 0x07,
} atm328p_timer_clock_t;

#endif
