#ifndef _ATM328P_SPI_CONFIG_H
#define _ATM328P_SPI_CONFIG_H

#include "Atm328pSpi.h"

#define ATM328P_SPI_IS_MASTER 1
#define ATM328P_SPI_IS_LITTLE_ENDIAN 0
#define ATM328P_SPI_CLOCK_POLARITY_IS_HIGH_IDLE 0
#define ATM328P_SPI_CLOCK_PHASE_IS_SAMPLE_ON_TRAILING 0
#define ATM328P_SPI_CLOCK_RATE ATM328P_SPI_CLOCK_DIV_4
#define ATM328P_SPI_USE_DOUBLE_SPEED 1

#endif
